### ISSUE TITLE
[Question] Yasnippets as part of rational-ide

### ISSUE THREAD

**Issue by cfclavijo** [SystemCrafters/crafted-emacs#168]
I know that **tempo** (or skeleton) provides **snippets** and it is part of emacs, however, **lsp servers** are using (AFAIK) a snippet syntax similar/compatible with **Yasnippet**, probably due to **VSCode'** _snippets syntax_.
**eglot** and **lsp-mode** are able to interpret the incoming snippet from the lsp-server and nicely expand it thanks to **Yasnippet**.
So, right now, _in my opinion,_ the default experience is not complete and makes you install Yasnippet on your own in order to take advantage of the Lsp-server.

What do you think about this?

**Comment by jeffbowman** [comment]
Thank you for starting this discussion. 

Your opinion is accurate in the sense the experience is not complete, and the decision was deliberate. We chose to create Rational Emacs following several principles, one is to prefer built-in packages, another is to provide a good starting point for hacking one's own Emacs configuration. 

Tempo and Skeleton are preferred over Yasnippet because they are built-in, VC mode is preferred over Magit because it is built-in, Eglot is preferred as it is closer to the built-in facilities than LSP and so on. I think an argument could be made that each of the eschewed packages are (a) more popular and (b) more widely used - nearly to the point of being the defacto standard for the features they provide. 

My preference with this project would be to stay closer to the "ivory tower" of the principles with which we started the project to allow as much freedom for the end user to provide the overrides or additions they prefer.   Part of that preference comes from knowing when to draw the line on what we configure and what we leave up to the user, another part is just accepting we can't please everyone with every configuration, package or omission of either. 

However, this is a intentionally a community driven project, and we encourage discussions like this from which we may choose to make changes! 

Feedback?

(@daviwil @jeastman )

**Comment by jeffbowman** [comment]
@cfclavijo , @daviwil  recently did a stream on writing his config with Rational Emacs where he talks about the goals of the project. Here is a link: https://youtu.be/2agRcDHgRAg?t=392 

Hope that helps with this discussion.

**Comment by mattmc3** [comment]
> Rational Emacs following several principles, one is to prefer built-in packages, another is to provide a good starting point for hacking one's own Emacs configuration.

There are definitely places where these goals are in conflict with one another, and that will certainly generate (passionate) discussion. For instance - Viper is built-in, but Rational decided to include Evil. I think most users will agree with that decision because Evil is such a well known and mature package, and functionally does way more than viper-mode. On the flip side, Rational confusingly includes doom-modeline which [arguably makes way less sense](https://github.com/SystemCrafters/rational-emacs/issues/44) given the alternative of having Rational enhance the built-in modeline.  It might help to clarify the calculus of how the decision is made to include an external package.

For my $0.02, yasnippets fits more in the Evil category to me than doom-modeline in terms of its popularity, maturity, and ubiquity. But, if I'm honest, I may only think that because I've never used tempo. Regardless, snippets are so essential that it would absolutely be worth having the maintainers take a position and add a `rational-snippets.el` to this project containing whatever snippet method fits with the project's calculus for choosing a dependancy.

**Comment by jeffbowman** [comment]
Closing in anticipation of Crafted Emacs V2
