### ISSUE TITLE
rational-editing modifies source files unsolicited

### ISSUE THREAD

**Issue by gendl** [SystemCrafters/crafted-emacs#175]
Hi,

 When I have `(require 'rational-editing)` in my `config.el`, it automatically "cleans up" whitespace from source code files for any file opened into a buffer in `prog-mode`. For a lot of my Common Lisp (`.lisp`) files at least, this has the effect of "untabifying" the buffer and putting it into a modified (unsaved) state (shown with one or two `*` in the mode-line) immediately upon opening. 

Consider whether this behavior might be more appropriate as an opt-in feature, a possibility mentioned today by @daviwil in #systemcrafters on libera.chat irc. 

Let me know if you could use an easy to replicate example. 

For now, I've suppressed the behavior by doing `M-x customize-group RET rational-editing RET`, changing the value of "Whitespace cleanup disabled modes" by adding `prog-mode` to the front of that list, and doing `[ Apply and Save ]`. 

This automatically added a form to my `~/.rational-emacs/custom.el` which looks like:

```
(custom-set-variables
   ...
  '(rational-editing-whitespace-cleanup-disabled-modes '(prog-mode makefile-mode))
   ...
 )
```

And with that customization it's no longer doing the unexpected modification. So it's not too hard to customize this behavior. But maybe it should default to not doing it. 

I'm not totally sure the best way to implement this as opt-out, but when a buffer is opened which has detected "messy" whitespace (does that mean "having any TAB characters?") then there could be a message informing the user of how to opt-in to automatic whitespace cleanup and/or how to run the command manually. 

Thanks,

 Dave

**Comment by jeffbowman** [comment]
Thanks @gendl for this report. Also, you did everything correctly for opting-out of the whitespace cleanup for programming modes in Emacs. 

The `rational-editing` module turns on whitespace cleanup for `prog-mode` (and thus for all derived modes). To opt-out, you can do exactly what you have done and customize the `rational-editing-whitespace-cleanup-disabled-modes` and add `prog-mode` to that list. You can also customize the `rational-editing-whitespace-cleanup-enabled-modes` and remove `prog-mode` from that list. Finally, you could turn off any whitespace cleanup by customizing the `whitespace-action` and setting that to nil (ie by choosing 'None' from the Value Menu if you are using the Easy Customization UI in Emacs rather than writing elisp in your config file). 

If you wish to run the whitespace cleanup manually, try `M-x whitespace-cleanup`. You may still need to configure `whitespace-action` to your liking and possibly disable `whitespace-mode` in your configuration. 

To completely opt-out with the least effort, do not add `(require 'rational-editing)` to your config. 

Does this explanation help? Also, did you try looking at the info node for the `rational-editing` module? Did that help you? (I'm curious if there is something there we can do to improve if it wasn't helpful to you. If you didn't look for it, that's fine too.  I'm interested to know what resources people might have tried so I can see if there is a way I can make them more effective)

**Comment by gendl** [comment]
Thanks @jeffbowman  yes the explanation helps. I haven't looked at info nodes yet - i need to learn to use the info system. What I did do was search for a customization-group and found one for rational-editing, so that's how I landed on the customization UI with those options. I tried setting `rational-editing-whitespace-cleanup-enabled-modes` to `nil` but that did not seem to take effect -- maybe I needed to restart to test that and didn't do so...

Anyway I'm all good for now, I just posted this issue because daviwil mentioned on IRC that this editing maybe should be opt-in instead of opt-out -- i have no strong opinion either way now that I'm clear on how to customize it.

**Comment by cfclavijo** [comment]
I have configured `whitespace-action` to only perform clean-ups when **saving** the buffer.
In my **config.erl** I have something like this

`(custom-set-variables
 '(whitespace-action '(auto-cleanup))
 )`
 
 info about `auto-cleanup`:   _cleanup any bogus whitespace when buffer is written._
 my go-to way of finding information is
 variables related: `C-h v`
 functions related: `C-h f`

**Comment by jeffbowman** [comment]
@gendl Is this issue resolved? (ie. can we close this, or is there more discussion needed?)

**Comment by jeffbowman** [comment]
Closing due to no further discussion
