### ISSUE TITLE
File is missing: Cannot open load file, No such file or directory, crafted-use-package

### ISSUE THREAD

**Issue by cwulfman** [SystemCrafters/crafted-emacs#215]
With fresh install of crafted-emacs and set-up with the example config files,  launching emacs produces this error

>File is missing: Cannot open load file, No such file or directory, crafted-use-package

this is because crafted-use-package is still being required in example-config.el:

https://github.com/SystemCrafters/crafted-emacs/blob/380d66fefe37a5b388e7205312591c9bf33d3ca2/examples/example-config.el#L22

**Comment by aniketgm** [comment]
`crafted-use-package`  is now simply `crafted-package`. Check the bootstrap folder. I was going to file the same issue. You beat me to it. Also, the link for the same is broken in the README under [Modules](https://github.com/SystemCrafters/crafted-emacs#modules) section.

Please correct me if I'm wrong here. From what I can deduce, one can now customize the package installer being used with `crafted-package` by setting the `crafted-package-system` variable (default is 'package, there is bootstrap for [straight.el](https://github.com/SystemCrafters/crafted-emacs/blob/380d66fefe37a5b388e7205312591c9bf33d3ca2/bootstrap/crafted-straight-bootstrap.el)).
However, I'm not sure how the customization would work if it's set to 'use-package. Others can explain it better I guess.

**Comment by jeffbowman** [comment]
`crafted-use-package` was removed to avoid confusion and redundancy on the configuration for `package.el`.  This allows the user to use `use-package` if they choose without impacting how the modules in _Crafted Emacs_ install packages.  Initially, `crafted-use-package` was provided as a way to have `use-package` installed for use on stream, or if a user wanted to use `use-package` out of the box.  That decision has since been reversed.  

The `crafted-package-install-package` macro is used by the modules to keep package installation consistent with the user's preferences by keeping a consistent interface with a configurable "backend"; currently either `package` or `straight`.  The user can use `crafted-package-install-package` if they choose or any other package front-end like `leaf` or `use-package`, or even call `package-install` or `straight-use-package` directly in their configuration (`config.el`).

I'll fix the example configurations. Thanks for bringing this up!
