### ISSUE TITLE
Add bookmarks to crafted startup page

### ISSUE THREAD

**Issue by ParetoOptimalDev** [SystemCrafters/crafted-emacs#232]
I recently setup Crafted Emacs for a non-technical user for some specific tasks.

I made them a series of bookmarks to certain files and dired directories.

This allowed me to teach them a minimal set of things to start immediately using crafted emacs with some domain specific elisp.

Basically it let me avoid teaching buffer/window navigation and keyboard shortcuts entirely along with the menu bar and context-menu-mode.

I realized that having a link like this or even a list of bookmarks like the recentf list makes emacs much more accessible in cases like mine, but also in general.

Thoughts?

**Comment by jeffbowman** [comment]
There was some discussion on making the `crafted-startup-screen` more customizable, that discussion has largely fizzed out at the moment.  The issue here would be constructing such a list and then putting it on the screen.  As this would imply a different mechanism than either `recentf` or `bookmarks` (ala `C-x r m` type of bookmark) that would have to be custom built... the result would be more like a "favorites" list of files to open.  Assuming such a list existed, adding it to the start screen is not difficult.

**Comment by jeffbowman** [comment]
Closing post v2 release.
