### ISSUE TITLE
How to bring up vertico on C-c C-x.

### ISSUE THREAD

**Issue by artelse** [SystemCrafters/crafted-emacs#240]
Topic explains the issue I try to solve. I just started with `crafted-emacs` and was used to vertico showing options for 'C-c` and `C-x`. Should this be configured separately?

**Comment by jeffbowman** [comment]
I'm not sure, as vertico is a completion UI, and usually `C-c` and `C-x` are bindings to commands so they don't usually show up in completion UIs.  `which-key` does this though, so that if you press `C-c` `which-key` would show the bindings associated with that prefix.  Same with `C-x`.  `M-x` is the interface to manually typing commands and `vertico` shows those correctly.

**Comment by jeffbowman** [comment]
If that answers your question, I'll close this issue (or you can) :-)

**Comment by artelse** [comment]
Forgot to ask if there is a community channel, discord or irc for regular questions or discussion. I don't want to raise 'issues' when they aren't really.

**Comment by jeffbowman** [comment]
On Discord, you can find System Crafters and there is a #crafted-emacs channel there.
