### ISSUE TITLE
*invalid* in mode line w/crafted-ui 

### ISSUE THREAD

**Issue by pablos-here** [SystemCrafters/crafted-emacs#264]
Hi,

On a fresh install, when I enable the `crafted-ui` module, I get **\*invalid\*** displayed in the mode line.  I tested with *scratch* and an `init.el` file.  Both get the message.

- This is a [screen scrape](https://i.imgur.com/UO05quL.png) showing the issue.
- This is the `custom.el` file I stripped down to isolate the issue:

```
(provide 'custom)
(require 'crafted-ui)
```

**Comment by jeffbowman** [comment]
Thanks for the report!

Once again, the culprit is Doom mode line.  Even when not in use, if it is only installed, it somehow breaks the mode-line, likely when `package.el` initializes the installed packages.  I have added an update to check if it is installed before toggling `doom-modeline-mode`, and for it's configuration, I have moved the installation to within the block where we check if the user wishes to use Doom mode line.  If that value is `nil` (the default) then the package is not installed. 

@pablos-here , if you would please pull from the master branch and test again.  Re-open this if you still have issues. 

I think this is the third issue we have had with Doom mode line, I'm probably going to remove it from the project in the near future.  Unless the community speaks up in favor of keeping it.

**Comment by pablos-here** [comment]
Fixed!  \o/

Thank you @jeffbowman for the quick turn-around!

**Comment by jeffbowman** [comment]
@erikLundstedt You might be interested in this fix as well.
