### ISSUE TITLE
[craftedv2beta] confusing auto-insertion prompt

### ISSUE THREAD

**Issue by bacchist** [SystemCrafters/crafted-emacs#300]
When Emacs is run for the first time following the guide, custom.el doesn't exist yet. Since auto-insert-mode is turned on in crafted-init-config.el before it is created, the first thing a new user sees is a confusing message saying: "Perform Emacs Lisp header auto-insertion? (y or n)"

Saying no just quietly creates the file and brings up the splash screen and everything is fine. This should just be the default behavior without prompting the user, especially given the disastrous UX that awaits them if they say yes for whatever reason.

At the very least, `touch custom.el` should be suggested in the guide.

**Comment by jvdydev** [comment]
Thank you for the issue.

I think this could be solved in a few ways (some of which you already suggested):
- suggest to create the file (not just to run `touch custom.el` ~> Windows users)
- explain to the user what is happening ("On first start, you will encounter ...")
- change the startup code to create the file if it's not present
  - would still explain why, but also automate it for the user

The modified `custom-file` code could maybe look like:
```emacs-lisp
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(if (file-exists-p custom-file)
  (load custom-file nil :nomessage)
  (make-empty-file custom-file))
```

I think creating the file would make sense so when moving a `crafted-emacs`-based configuration between machines, it would "just work" instead of having to remember to create the custom-file manually (or having to deal with the popup).

**Comment by jeffbowman** [comment]
Provided a fix for this issue for Crafted Emacs v2 Beta.  Thanks for reporting.  I'll back port to the main branch and close this once I do.
