### ISSUE TITLE
Provide option for easier module loading.

### ISSUE THREAD

**Issue by UristMcLisper** [SystemCrafters/crafted-emacs#321]
I wanted almost all modules enabled and found it tedious to write a require for each (twice). I'd prefer documentation to provide a snippet that I can copy-paste and (un-)comment a few things, like what doom provides with init.el. I'd like to make a PR.

**Comment by jvdydev** [comment]
Interesting thought, I wonder if such a function would be more likely to end up in a documentation snippet instead (something like "I want everything, is there a faster way?").

I think the code you provided as a "quick fix" would need a bit of transformation. (probably want to pass symbol-list like `'(crafted-defaults crafted-writing)` and use `member` instead of regex, checks if the module actually has packages (e.g. `crafted-defaults` doesn't), adding the packages to the selected-packages list instead of just loading a file (generally using `require`), just some thoughts).

On a principles level, I'm not sure if this would abstract too much away (hence I'd rather put it in documentation so people can understand what they are using), hope that makes sense.

**Comment by UristMcLisper** [comment]
I'll clarify. I'm proposing this snippet to be mentioned in Getting Started README and 4.2.2 Emacs Initialization:
```
(crafted-emacs-load-modules
 '(completion
   defaults
   ide
   lisp
   org
   package
   speedbar
   ui
   updates
   workspaces
   writting
   ;; home
   ;; evil
   ;; osx
   ;; screencast
   ))
```
Append"-packages" or "-config" to any of symbols to choose it only.

**Comment by jvdydev** [comment]
Sorry, I was/am rather tired reading this, however I think I understand.

I don't think putting a `crafted-emacs-load-modules` function into the project would make a ton of sense (ignore this part if this was not the intention).
It's not much different from a package installation macro (except it being a function).
I think this would fit more into an example documentation to be pasted into a users `init.el` file (both the function and the function call).

Maybe @jeffbowman has some thoughts as well.

**Comment by jvdydev** [comment]
I'm also a little confused as your initial issue provided a way to exclude packages while the second example seems to be more focused on including packages (and that's how I remember it working in Doom Emacs as well back when I used it).

**Comment by UristMcLisper** [comment]
Yes, my bad. Removed it

**Comment by jeffbowman** [comment]
> I don't think putting a crafted-emacs-load-modules function into the project would make a ton of sense.
It's not much different from a package installation macro.
I think this would fit more into an example documentation to be pasted into a users init.el

I agree. 

This probably belongs more in a "Tips and Tricks" section in the documentation.

**Comment by jeffbowman** [comment]
Closing this as there is no further discussion, and v2 has been released
