### ISSUE TITLE
`crafted-init-config` automatically finding directory possibly confounded by submodule use

### ISSUE THREAD

**Issue by Remillard** [SystemCrafters/crafted-emacs#390]
### Operating System

Windows

### Additional Operating System information

10

### Emacs Version

29

### Emacs Configuration Details

- [ ] Native Compilation
- [ ] pGTK
- [ ] alternative package manager (use-package, straight.el, ...)

### Anything else that may be related to the issue you're having?

This is a pretty vanilla-ish installation in Windows of Emacs 29.1.  It had previously called the Crafted Emacs early-lisp file and the issue seemed to be in init.el.

### What happened?

I keep my `~/.emacs.d/` configuration under version control and when adding Crafted Emacs, I chose to include it as a submodule of my current repository rather than it's own to keep the organization sorted.  So its home location is `~/.emacs.d/crafted-emacs/` rather than a separate directory elsewhere.  I was following along with the examples and it pretty quickly became evident that when it got to a later step like `(require 'crafted-completion-packages)` that it had no idea where the modules directory existed.

I poked around in the `crafted-init-config.el` file and it appears as if the discovery of its home is predicated on using `git`.  I don't know if the fact that I had it as a submodule may be confusing this routine in discovering where it is located.

It's also possible it's due to this being Windows.  Normally everything works fine, but occasionally there are quirks.

I did get around this by declaring: `(setq crafted-emacs-home "~/.emacs.d/crafted-emacs/")` before calling `crafted-init-config` and everything works fine.  This issue is just so you are aware that the self-discovery aspect may have some quirks.

### What should have happened?

Technically, it should not have been necessary to put the `crafted-emacs-home` since a self discovery method exists.

**Comment by jeffbowman** [comment]
Thanks! 

Will need to look into how we might detect submodules in scenarios like this.  Probably need to update the documentation with hints about setting the `crafted-emacs-home` value before loading `crafted-init-config` in scenarios like this.

**Comment by Remillard** [comment]
Is relying on git necessary here?  Is there a way for the routines in `crafted-init-config.el` to know where the file exists?  If you're using git for identifying the project head, there's no real reason to believe that the user has modified the repository tree.  Could possibly derive the project root from the location of the initial file.

Otherwise, certainly works to set the directory and I'm glad that it was written to check for this variable and use it when set.  Solved my problem completely.  It was just the automatic method that didn't seem to work.  Anyway, hope the report helps.

**Comment by jeffbowman** [comment]
> Something like this should get the same result:

    (when (null crafted-emacs-home)
      (setq crafted-emacs-home (expand-file-name (vc-find-root load-file-name "modules"))))

I was, quite literally, just testing this.  I think I originally used `project-root` as it provided what I needed, and I use projects, and checking this code out from `git` would give the expected result.  However, if the project is downloaded but not checked out using `git`, then what?  That particular piece still needs some re-evaluation.  But for `git submodules`, which this issue is about, the `vc-find-root` is sufficient as well as in cases where the project was cloned to it's own directory.

**Comment by jvdydev** [comment]
For the other case, we could go the (potentially fragile) route of going of "path relative to currently executing file" route.
Otherwise, I'd propose a good error message explaining that it cannot locate the crafted-emacs installation and ask the user to set the `crafted-emacs-home` variable manually.

**Comment by jeffbowman** [comment]
So, it turns out, `vc-find-root` even works when there is not `.git` or `.github` directory (as if you had just downloaded the project source).

**Comment by Remillard** [comment]
May have been a Windows issue then, or combined Windows+git issue.  I'm pretty sure it wasn't exactly a "me" issue as at the point where I call that, I've done:
1) Crafted Emacs early-init.el
2) Snippet of code to load `custom.el`
3) Set temporary file directory variable.
4) `(load ~/.emacs.d/crafted-emacs/modules/crafted-init-config")`

Then following that, a little blurp about setting up `use-package` then I call my first `(require 'crafted-xxx-package)` line.  None of these things are elaborate enough to make me think it was my situation where `crafted-init-config` couldn't automatically set the `crafted-emacs-home` variable.  (So for now, step 3.5 is setting that variable, then running `crafted-init-config` and everything loads just fine, so that's the only issue I'm aware of.

**Comment by jvdydev** [comment]
> So, it turns out, vc-find-root even works when there is not .git or .github directory (as if > you had just downloaded the project source).

That's interesting, then again it was the *alternative* version in our code (when there was no git), so clearly someone knew that in the past.

> May have been a Windows issue then, or combined Windows+git issue.

Well, the current iteration of the code *does* seem to break on Linux too (from my testing) if in a submodule (or crafted-emacs not being the root of the git-tree) and git is found in `PATH`.

I think moving forward, this section of code needs a little more checking that we're doing the right thing and otherwise actively signaling to the users that there is something they need to do manually (for one reason or another).

**Comment by sthesing** [comment]
Closing this, because it's addressed by #391.
Thanks to everyone involved.
@Remillard feel free to reopen if necessary.
