### ISSUE TITLE
what do everyone here think about adding a leader-key i.e using general.el or similar 

### ISSUE THREAD

**Issue by erikLundstedt** [SystemCrafters/crafted-emacs#76]
I have is in my own config and im thinking it might be nice to have a global way to define keys etc

i myself use "SPC" as i started out using doom-emacs but that could be configurable,right?

it would be great to be able to do something like

I guess we would want some whay to have module-specific first-keys(`f` in this example)
```emacs-lisp
(when rational-leader-enabled
    (rational/general-keys 'relevant-mode-here
    ;;some keybind definitions here
    "f b b" (some-action-here :which-key "this is optional" )
    )
)
```

**Comment by jeffbowman** [comment]
I prefer standard Emacs keys. So, I don't use evil mode or other modes similar to that, and I'm not terribly interested in a leader-key configuration.  I think a module with this setup would make sense (I can choose not to use it, others can choose to use it).

**Comment by Gavinok** [comment]
In my opinion there isn't really much benefit here. Evil already provides leader functionality. If we wanted to emulate some doom bindings maybe someone could make a module for it.

**Comment by angrybacon** [comment]
I think there's a thin line between making a base pool of sensible and cautious defaults vs. making a new configuration (with or without a wizard to set it up) like what Doom and Spacemacs might provide to the community already. I think this kind of question will come back in various forms and the README could use some section to clarify what we want in this repository vs. what should be left to the user to implement themselves the way they see fit. 

Not that I'm very much against the feature, but I think there are a lot of ways to go about it and that should be a clear indicator that *crafters* would rather implement their leader key in their preferred way 🤓

**Comment by theophilusx** [comment]
I'm also not convinced re: a leader key module or adding modules to make transition from other setups easier (guidelines to assist in migration could be something added to documentation). 

The main reason I don't like the idea is I think it will miss an important opportunity. One of the very interesting aspects of rational eamcs is the use of vertico and embark. In particular, embark brings a different 'style' of UI which I find very interesting (i.e. the inversion of UI from action -> thing to thing -> action). IMO this inversion makes the UI model of spacemacs/doom style hierarchical menus of actions on a leader key with which key etc less valuable/useful. To really get this benefit, it is important to have a UI which encourages people to select the 'thing' and then the action. Making it easy for people to clone the UI styule they are familiar with will work against this. 

Note that I'm not against general.el - I think it is actually are really interesting and powerful module and it could be something rational emacs may want to use/include. I would just prefer it not be used to create a less functional clone of spacemaces/doom. 

If we did decide to add a leader key configuration, I would consider adding one which creates bindings that focus on selecting 'things' rather than one which focuses on selecting actions.

**Comment by erikLundstedt** [comment]
> In my opinion there isn't really much benefit here. Evil already provides leader functionality. If we wanted to emulate some doom bindings maybe someone could make a module for it.



> Evil already provides leader functionality
how do i do that?
i found a package (evil-leader) that does it but it doesnt seem to do anything much differently to general.el
is there a way to do it with just evil?

**Comment by erikLundstedt** [comment]
> I think there's a thin line between making a base pool of sensible and cautious defaults vs. making a new configuration (with or without a wizard to set it up) like what Doom and Spacemacs might provide to the community already. I think this kind of question will come back in various forms and the README could use some section to clarify what we want in this repository vs. what should be left to the user to implement themselves the way they see fit.
> 
> Not that I'm very much against the feature, but I think there are a lot of ways to go about it and that should be a clear indicator that _crafters_ would rather implement their leader key in their preferred way nerd_face



I am not talking about forcing anyone to use it, nor am i sugesting trying to replace all of dooms keybinds
what i am talking about is to add the ability for module maintainers to easily add leader-keybinds for us who actually want it

this would still only be loaded on user request(with a variable) or if the required packages are installed
this is what we already do with 
```emacs-lisp
(with-eval-after-load 'evil
  (define-key vertico-map (kbd "C-j") 'vertico-next)
  (define-key vertico-map (kbd "C-k") 'vertico-previous)
  (define-key vertico-map (kbd "M-h") 'vertico-directory-up))
```
so what the developer would do is something like
```emacs-lisp
(with-eval-after-load 'evil-leader
   (evil-leader/set-key "key" 'some-command-or-action)
)
```
or equivalent with general.el

**Comment by jeffbowman** [comment]
There has not been much further discussion on this, and there doesn't seem to be much support for it. Can this issue be closed?

**Comment by jeffbowman** [comment]
Closing as there has been no further discussion.
